name: flutter_core_ui_kit
description: Another flutter ui kit
version: 0.0.1

environment:
  sdk: ">=2.13.4 <3.0.0"
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter

  # Graphics packages
  cached_network_image: ^3.1.0+1
  adaptive_dialog: ^1.2.0
  shimmer: ^2.0.0
  app_settings: ^4.1.1 # only mobile

  # file manager
  image_picker: ^0.8.4+4
  file_picker: ^4.2.0
  crop_your_image: ^0.6.0+1
  path_provider: ^2.0.6 # only mobile

  auto_size_text: ^3.0.0
  reactive_forms: any
  loadmore: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
